### ISSUE TITLE
All tests are failed

### ISSUE THREAD

**Issue by ka8725** [sinisterchipmunk/rspec-prof#10]
Failure/Error: Unable to find matching line from backtrace
     ArgumentError:
       wrong number of arguments (2 for 1)
     # /usr/local/opt/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-prof-0.0.5/lib/rspec-prof/filename_helpers.rb:19:in `path_for'
     # /usr/local/opt/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-prof-0.0.5/lib/rspec-prof/filename_helpers.rb:21:in `path_for'
     # /usr/local/opt/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-prof-0.0.5/lib/rspec-prof/filename_helpers.rb:28:in `filename_for'
     # /usr/local/opt/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rspec-prof-0.0.5/lib/rspec-prof.rb:72:in `block (2 levels) in <top (required)>'

**Comment by sinisterchipmunk** [comment]
Closing this as the new version has (finally) been released. Thanks for reporting!
